### ISSUE TITLE
plot all regions, and highlight some of them 

### ISSUE THREAD

**Issue by Conxz** [LCBC-UiO/ggseg#18]
Hi, I would like to create a figure like below, with all regions' values being plotted, and some regions being highlighted with boundary line. I tried the parameter 'color', but it seems that this parameter only accept one value, so I could not specify different colors for different regions in this way. 
Could you help? Thanks. 
![image](https://user-images.githubusercontent.com/712044/68533287-e5f68380-0326-11ea-8295-f674d21edd04.png)

**Comment by Athanasiamo** [comment]
Hi! 

You should be able to do this in the same way as you map fill to different colours. Instead of specifying colour outside the mapping, placing it inside and refering to some variable that scales the colour should do it.

Since I dont see you original code or data, I'm guessing it would be something like

`ggseg(results, mapping(fill=effect_size, colour = highlight_variable))`

**Comment by Conxz** [comment]
Thanks Athanasia! It works well now!
