### ISSUE TITLE
geom_label with ggseg

### ISSUE THREAD

**Issue by butellyn** [LCBC-UiO/ggseg#25]
Have you found a way to use geom_label with a ggseg object? When I use it, every pixel seems to get labeled. How would you go about only plotting unique labels?

**Comment by Athanasiamo** [comment]
Hi!

It's a little tricky, you will need a separate data frame for the labels alone, having calculated the center of gravity or areal-center of each geom. 

This is currently not something we have implemented, and is likely something that will need quite some adapting to make work. Especially if using the `position = "stacked"` option which is calculated internally. 

This example is not ideal, because just taking the mean of x and y for each label is not actually hitting the target. But I hope it can give you an idea of what you'd need to do.
I'm also using geoms from the ggrepel-package, which is great when you have many labels and want to avoid them overplotting eachother.


``` r
library(tidyverse)
library(ggseg)

# for dispersed brain
labels <- dk %>% 
  unnest(cols = ggseg) %>% 
  group_by(label) %>% 
  summarise(.lat =  mean(.lat), .long = mean(.long))

ggseg(show.legend = FALSE) + 
  ggrepel::geom_label_repel(
    data = labels, inherit.aes = FALSE, 
    size=3,
    mapping = aes(x = .long, y=.lat, label=label))
```

![](https://i.imgur.com/MdM0vn4.png)

``` r

# for stacked brain

labels <- dk %>% 
  unnest(cols = ggseg) %>% 
  ggseg:::stack_brain() %>% 
  group_by(label) %>% 
  summarise(.lat =  mean(.lat), .long = mean(.long))

ggseg(show.legend = FALSE, position = "stacked") + 
  ggrepel::geom_label_repel(
    data = labels, inherit.aes = FALSE, 
    size=3,
    mapping = aes(x = .long, y=.lat, label=label))
```

![](https://i.imgur.com/5BKt9nm.png)

<sup>Created on 2020-03-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by butellyn** [comment]
Hi! This solution no longer works with ggseg v 1.6.00 (it worked with 1.1.5, which is the last version I used). It looks like the ggseg object has changed considerably, as the .long and .lat columns no longer exist. How would you recommend doing this now?

**Comment by Athanasiamo** [comment]
Hi @butellyn 

You can still do it the old way, just force the new `brain-atlas` object into a `ggseg-atlas` object with `as_ggseg_atlas()` and the familiar atlas from before will be there.

But, I'd recommend rather using the new version, together with the workflow we describe [in the vignette about using brain-atlas with `geom_sf()`](https://lcbc-uio.github.io/ggseg/articles/geom-sf.html]. This also has a section about adding labels using this particular workflow, that we believe is a much neater way to work.

**Comment by butellyn** [comment]
This worked. Thanks!
