### ISSUE TITLE
Is it possible to highlight some regions only?

### ISSUE THREAD

**Issue by jenhungwang2019** [LCBC-UiO/ggseg#26]
Hi,
Is it possible to highlight only some regions with different colors and add some corresponding labels aside?
I tried to apply the ggseg(), but it doesn't work sometimes.
My source code:
someData = data.frame(
  area = c("caudal anterior cingulate","isthmus cingulate",
           "medial orbito frontal","parahippocampal",
           "posterior cingulate","precuneus",
           "rostral anterior cingulate","supramarginal"), 
  p = sample(seq(0,.5,.001), 8),
  stringsAsFactors = FALSE)
# Condition 1=>It works!! Hight some regions with different colors.
ggseg(.data=someData, colour="black", mapping=aes(fill=p)) +
  theme_void() +
  scale_fill_gradient(low="firebrick",high="goldenrod") +
  labs(title="Testing", fill="p-value")
Output:
![Condition1](https://user-images.githubusercontent.com/52772160/77546745-460d5100-6ee7-11ea-9127-d63158d57e26.png)

# Condition 2=>Not as my wish!! All regions were displayed in the image generated.
ggseg(.data=someData, colour="black", size=.7,mapping=aes(fill=area),
      position = "stacked") +
  scale_fill_brain("dkt") +
  theme_void()
Output:
![Condition2](https://user-images.githubusercontent.com/52772160/77546778-53c2d680-6ee7-11ea-9f64-6684001b14b4.png)

Is there something wrong?

**Comment by Athanasiamo** [comment]
Hi!

firstly, I recommend updating ggseg, as there was a change lately that will affect whether you can run the examples below. We changed the name "area" to "region", because it was conflicting with something else. 

This is expected behaviour. 
The "area" (now "region") column when plotting becomes populated with every region in the atlas, which is why is is plotting the way it is. 

``` r
library(ggseg)
#> Loading required package: ggplot2

someData = data.frame(
  region = c("caudal anterior cingulate","isthmus cingulate",
           "medial orbitofrontal","parahippocampal",
           "posterior cingulate","precuneus",
           "rostral anterior cingulate","supramarginal"),
  p = sample(seq(0,.5,.001), 8),
  stringsAsFactors = FALSE)

ggseg(.data=someData, colour="black", size=.7,
      mapping=aes(fill=region),
      position = "stacked") +
  scale_fill_brain("dk") +
  theme_void()
```

![](https://i.imgur.com/dGkB7DP.png)


You need to make a copy of the region, into a column name that does _not_ match the atlas, and the pass that to `fill` inside the function. 

``` r
someData$region2 <- someData$region
ggseg(.data=someData, colour="black", size=.7,
      mapping=aes(fill=region2),
      position = "stacked") +
  scale_fill_brain("dk") +
  theme_void()
```

![](https://i.imgur.com/ElSimil.png)

<sup>Created on 2020-03-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jenhungwang2019** [comment]
Hi,
Thanks for your quick response.
It works.
However, some error happened while I was updating ggseg.
Original command:
remotes::install_github("LCBC-UiO/ggseg", build_vignettes = TRUE)
I modified as:
remotes::install_github("LCBC-UiO/ggseg", build_vignettes = FALSE)
What's the difference if I changed the setting to FALSE?
By the way, is it possible to change 'region2' to another word, such as 'region' or 'area'?
Thanks again.

**Comment by Athanasiamo** [comment]
Hi. 

Happy it worked! Omitting vignettes has no real consequence for you, unless you are trying to access the tutorials on using ggseg (vignettes) locally. Since our vignettes are online, I think this has no consequence for you.

You can call `region2` whatever you like that _is not a name already in the ggseg atlas_. The data you provide to the `ggseg` function, and the atlas you are plotting must share at minimum 1 column of the same name, with similar contents, in order to match data to the atlas. This is what you are doing with the "region" column. However, once merged, region will contain _all regions of the atlas_ including those that are not in your data. Do fill the polygons with colour only for the regions present in your data, you need another column. 

Hope this is understandable.

Otherwise, I also suggest you read and familiarise yourself with ggplot2, which is the package this is all based on. Which hopefully will help you understand better what is going on and to achieve your wanted results.

**Comment by jenhungwang2019** [comment]
Hi,
I got it. Thanks a lot.
