### ISSUE TITLE
Add feature to put labels on top of each region?

### ISSUE THREAD

**Issue by monicathieu** [LCBC-UiO/ggseg#45]
Hi again,

Thank you once more for making such useful brain viz packages! I am making some 2D brain plots for a presentation, and wanted to figure out a way to put ROI labels on top of each region on the ggseg plots themselves (as opposed to putting text boxes on myself in PowerPoint or something).

I figured out how to do it by the following--it's rather hacky:

```r
library(tidyverse)
library(ggseg)

dk_labels <- dk %>%
  unnest(ggseg) %>%
  # Need to use internal function to coerce .long and .lat coords for position = "stacked"
  ggseg:::stack_brain() %>%
  # Must summarize to get one lat/long for each ROI label, not one for each perimeter point
  group_by(hemi, region, side, label, .id, .subid) %>%
  # Not perfect but puts each label sort of in the middle of its region
  summarize(.long = mean(.long), .lat = mean(.lat), .groups = "drop") %>% 
  # Because sometimes a single ROI appears to have multiple .id values, functionality unknown to me
  distinct(hemi, region, side, .keep_all = TRUE)

ggseg(mapping = aes(fill = region), position = "stacked") +
  geom_text(aes(label = region), data = dk_labels, size = 2) +
  scale_fill_brain() +
  guides(fill = FALSE)
```

![image](https://user-images.githubusercontent.com/9875687/94967881-f16a1480-04cd-11eb-86b2-62798f5108af.png)

You can see that this looks kind of insane, but essentially provides the desired functionality. For my purposes this works, because I've been filtering the labels dataframe to only label certain regions (e.g. those where some statistic exceeds a threshold). That helps avoid the overplotting issue, as that way there aren't that many labels on each hemisphere.

(Note that it _doesn't_ work to add `geom_text` without a custom `data` argument that's been reduced to one row per ROI label. I tried it that way using the data already inside `ggseg()` and it tries plotting a label for every perimeter point of every ROI. Eep!)

Do you think this might be a feature to add to a future version of the package? If so, definitely doesn't have to be the way I coded it above, but maybe you'll find the above helpful.

---

PS: Not sure if this should be split out into another issue, but `theme_darkbrain()` is not passing the `text.size` and `text.family` arguments into `ggplot2::theme()`, as `theme_brain()` and `theme_custombrain()` are. I think that's a super small fix!

**Comment by Athanasiamo** [comment]
Hi!

Thank you for this. This is something we have been hoping to integrated with a large upcoming update. 
There are some problems we have encountered so far making this a little tricky, but hopefully we can get them sorted.

And thank you for noting that theme_darkbrain is not passing arguments as expected! It's fixed in the dev-branch, so its going to be fixed soon in the master branch too :)

**Comment by Athanasiamo** [comment]
Hi @monicathieu !

We have now released the package with some new features. In particular we have moved the atlases to using simple features rather than polygons, meaning that you now can, with an alternate pipeline, more easily plot with labels/text. 

Please see the new package vignette on how to do this, [Using atlases with geom_sf](https://lcbc-uio.github.io/ggseg/articles/geom-sf.html)

**Comment by monicathieu** [comment]
Oh this looks fantastic, thank you! Excited to try out the new feature.
