### ISSUE TITLE
geom_brain has no orientation labels

### ISSUE THREAD

**Issue by ElijahMak** [LCBC-UiO/ggseg#49]
Hi,

Is geom_brain able to plot the orientation (i.e. hemisphere, left, right etc)? This is automatically produced by ggseg, so I am not sure whether an extra command is needed for geom_brain. I find geom_brain faster in the plotting so I am keen to stick with it.

<img width="767" alt="image" src="https://user-images.githubusercontent.com/20706794/102152240-7da09c80-3e6c-11eb-925c-b43204fa6485.png">

Thanks again for this fantastic package!

**Comment by Athanasiamo** [comment]
Hi. 

Because of how the geoms work, we dont yet have an easy way for you to add the orientations.
Best solution we can give is manually adding them through the scales.
Given how you position the brain in the plot, you might need to alter the coordinates.
Also, other atlases might have other dimensions, so we currently are unable to capture this easily by default.


``` r
library(ggseg)
#> Loading required package: ggplot2

ggplot() + 
  geom_brain(atlas = dk, show.legend = FALSE,
             position = position_brain(hemi ~ side)) +
  theme_brain() +
  scale_x_continuous(breaks = c(140, 520), 
                     labels = c("lateral", "medial")) +
  scale_y_continuous(breaks = c(100, 340), 
                     labels = c("left", "right"))
```

![](https://i.imgur.com/7VUJ3RO.png)

<sup>Created on 2020-12-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ElijahMak** [comment]
It worked. Thanks for guidance, Athanasia.

Out of curiosity, in general which method would you recommend for users? geom_brain or ggseg?

Best Wishes,
Elijah

**Comment by Athanasiamo** [comment]
Great!

I plan on soft-deprecating `ggseg()` as a function. It will be more sensitive to changes in underlying packages than `geom_brain()` and is also slower. We will keep it around for  a good while, but I dont plan on doing alot of continued development on in. 

In short: switch to `geom_brain`. We are working on companion functions to help add things like orientation labels etc.
