### ISSUE TITLE
Change color of border between regions

### ISSUE THREAD

**Issue by dbaranger** [LCBC-UiO/ggseg#5]
Hi! Love this package. 
I think in an earlier version it was possible to adjust the color and size of the border surrounding each individual region in an atlas? ie. ggseg(...color = "black", size=1). Currently it only adjusts the border of the entire brain. It would be great to get the old functionality back, so that it's easier to distinguish neighboring regions. 
Thanks!

**Comment by Athanasiamo** [comment]
Hi! Thanks for using our package and providing feedback.

If I understand you correctly, you should be able to control the regional boundaries with the mapping function:

`ggseg(mapping=ggplot2::aes(colour=area))` should produce different borders for each area.

![image](https://user-images.githubusercontent.com/14014329/44937038-9b1eca80-ad77-11e8-9494-c91416a273fb.png)

**Comment by Athanasiamo** [comment]
I shouldnt reply to tickets too late in the evening, I missed your point.

Indeed, we needed to alter how this was handled, in order to facilitate the possibility of having varying borders also. (Like my image above). This means that once we have provided something to `mapping` or to `data`, any handling of colours, fill, size etc. need to be handled by mapping.

I will try to create a better solution for this in the future, hopefully after next week.

So far, you can work around it like so:

`ggseg(mapping=ggplot2::aes(colour=I("grey"), size=I(1)))`

![image](https://user-images.githubusercontent.com/14014329/44944116-84a55d00-add1-11e8-9e0e-43ac7ddcb8db.png)

**Comment by dbaranger** [comment]
Great, thank you for the fast reply! That fix worked easily.

**Comment by Athanasiamo** [comment]
Just wanted to let you know, that I got time to sit down and do some more fixes.

The code for ggseg has been simplified, with some redundancy removed. 
This means I could rearrange the code, so that arguments to `ggseg` will behave more like typical ggplot arguments.

`aes` still need to be provided as `mapping=aes(...)`, but other ggplot arguments like colour, size etc can be provided in normal syntax and should work.

`ggseg(colour="black",mapping=aes(fill=area), show.legend=F)`

![image](https://user-images.githubusercontent.com/14014329/44949221-9288cb80-ae2d-11e8-86b0-dfade4e110ec.png)

Note, that if you want to control to colour of the medial wall or other NA values, this must now be supplied as a scale.

`ggseg(colour="black",mapping=aes(fill=area), show.legend=F) + scale_fill_brain(na.value="transparent")`
![image](https://user-images.githubusercontent.com/14014329/44949230-ded40b80-ae2d-11e8-8f2e-a5d9dc3a30cb.png)

Thank you for pushing me to look into this. I think the code and functionality is much improved.

**Comment by dbaranger** [comment]
Thanks! That's a lot more straightforward. 
Two suggestions for the future documentation. 
1 - maybe including a table of how each area needs to be labeled, since the system seems to be relatively inflexible on that front (not necessarily a bad thing). 
2 - including an example of applying a different color scale, with limits that extend beyond the data, since that's probably something a lot of people (like me!) would want to do. 

Anyway, thanks for the great package! Here's an example of a figure I'm working on, using it. 
![ffibpd_meta3](https://user-images.githubusercontent.com/25041809/44991881-93bc1480-af63-11e8-90eb-02153a1353d9.jpg)

**Comment by Athanasiamo** [comment]
Thank you for the suggestions! I'll work on adding stuff to the vignette (or making more vignettes for explanations of more complex features).

**Comment by Athanasiamo** [comment]
Ah. The give and take of writing code. As a result of the aesthetics fix, it complicated how you can provide external data over multiple facets. 

I've added information on this in the main vignette, and have also added another vignette called `externalData`, which I hope will make it understandable why it is happening, and also how to work with it.

I've also added a couple of examples of using different scales. Though it should function like any ggplot2 scale, and can be learned by for instance: https://www3.nd.edu/~steve/computing_with_data/12_Scales_themes/scales_themes.html

**Comment by jaimienav** [comment]
Hi dbaranger! How were you able to create the figure with only 6 regions colored for subcortical volume? I am trying to do the same thing and am having trouble.
